"""Add relationship between Product and Sale

Revision ID: 773e5cd6d8ad
Revises: 1024edb7e1cd
Create Date: 2024-09-21 01:44:12.462158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '773e5cd6d8ad'
down_revision: Union[str, None] = '1024edb7e1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('sales', 'date_created',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.alter_column('sales', 'date_created',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('sales', 'total_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.alter_column('products', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###
